//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Views_User_ChiTietTinTuc_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Views_User_ChiTietTinTuc_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\ChiTietTinTuc.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\ChiTietTinTuc.cshtml"
  
    ViewBag.Title = "ChiTietTinTuc";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";


#line default
#line hidden

#line 3 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\ChiTietTinTuc.cshtml"
       __o = Html.DisplayFor(model => model.TenTinTuc)tml.DisplayNameFor(model => model.TenTinTuc);


#line default
#line hidden

#line 4 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\UsDisplayNameForTinTuc.cshtml"
ChiTieto = Html.DisplayFor(model => model.TenTinTuc);


#line default
#line hidden

#line 5 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\UsDisplayForuc.cshtml"
       __o = Html.DisplayNameFor(model => model.ChiTiet);


#line default
#line hidden

#line 6 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\UsDisplayNameForTinTuc.cshtml"
AnhBia__o = Html.DisplayFor(model => model.ChiTiet);


#line default
#line hidden

#line 7 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\UsDisplayForuc.cshtml"
       __o = Html.DisplayNameFor(model => model.AnhBia);


#line default
#line hidden

#line 8 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\UsDisplayNameForTinTuc.cshtml"
NgayCapNhat __o = Html.DisplayFor(model => model.AnhBia);


#line default
#line hidden

#line 9 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\UsDisplayForuc.cshtml"
       __o = Html.DisplayNameFor(model => model.NgayCapNhat);


#line default
#line hidden

#line 10 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\UsDisplayNameForTinTuc.cshtml"
MaCD= Html.DisplayFor(model => model.NgayCapNhat);


#line default
#line hidden

#line 11 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\UsDisplayForuc.cshtml"
       __o = Html.DisplayNameFor(model => model.MaCD);


#line default
#line hidden

#line 12 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_newws\Views\UsActionLinkT"Edit", "Edit", new { id.chModel
MaTinTuc }   __o = Html.DisplayFor(model => model.MaCD);


#line default
#line hidden

#line 13 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\ChiTietTinTuc.cshtml"
__o = Html.ActionLink("Back to List", "Index");


#line default
#line hidden
}
}
}
