//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Dangnhap_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Dangnhap_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\Dangnhap.cshtml"
  
    Layout = null;


#line default
#line hidden

#line 2 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\Dangnhap.cshtml"
                    using (Html.BeginForm())
                    {
                        

#line default
#line hidden

#line 3 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\Dangnhap.cshtml"
                            __o = Url.Action("Index", "Home");


#line default
#line hidden

#line 4 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\Dangnhap.cshtml"
                                                                                                                          
                        

#line default
#line hidden

#line 5 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\Dangnhap.cshtml"
                                                                                                  
                        

#line default
#line hidden

#line 6 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\Dangnhap.cshtml"
                       __o = ViewBag.ThongBao;


#line default
#line hidden

#line 7 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\Dangnhap.cshtml"
                                                  
                        

#line default
#line hidden

#line 8 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\Dangnhap.cshtml"
                   __o = Html.ValidationSummary(true);


#line default
#line hidden

#line 9 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\Dangnhap.cshtml"
                                                     
                        

#line default
#line hidden

#line 10 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\Dangnhap.cshtml"
                       __o = Html.TextBox("TenDN");


#line default
#line hidden

#line 11 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\Dangnhap.cshtml"
                       __o = ViewData["Loi1"];


#line default
#line hidden

#line 12 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\Dangnhap.cshtml"
                              

                        

#line default
#line hidden

#line 13 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\Dangnhap.cshtml"
                       __o = Html.Password("Matkhau");


#line default
#line hidden

#line 14 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\Dangnhap.cshtml"
                       __o = ViewData["Loi2"];


#line default
#line hidden

#line 15 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\Dangnhap.cshtml"
                              
                        

#line default
#line hidden

#line 16 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\Dangnhap.cshtml"
                                                                

                        

#line default
#line hidden

#line 17 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\Dangnhap.cshtml"
                              
                    }

#line default
#line hidden

#line 18 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\Dangnhap.cshtml"
                                           __o = Url.Action("Dangky", "User");


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Dangnhap_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Dangnhap_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\binhh\AppData\Local\Temp\1CC00654114D7F8D84994677BD2025E9DB2F\3\24_news\24_news\Views\User\Dangnhap.cshtml"
  
    ViewBag.Title = "Dangnhap";
    Layout = "~/Views/Shared/_LayoutLogin.cshtml";


#line default
#line hidden

#line 2 "C:\Users\binhh\AppData\Local\Temp\1CC00654114D7F8D84994677BD2025E9DB2F\3\24_news\24_\Views\User\Dangnhap.cshtml"
        using (Html.BeginForm())
        {
            

#line default
#line hidden

#line 3 "C:\Users\binhh\AppData\Local\Temp\1CC00654114D7F8D84994677BD2025E9DB2F\3\24_news\24_news\Views\User\Dangnhap.cshtml"
       __o = Html.ValidationSummary(true);


#line default
#line hidden

#line 4 "C:\Users\binhh\AppData\Local\Temp\1CC00654114D7F8D84994677BD2025E9DB2F\3\24_ne4_news\Views\User\Dangnhap.cshtml"
                                         
        

#line default
#line hidden

#line 5 "C:\Users\binhh\AppData\Local\Temp\1CC00654114D7F8D4677BD2025E9DB2F\3\24_news\24_news\Views\User\Dangnhap.cshtml"
             
        

#line default
#line hidden

#line 6 "C:\Users\binhh\AppData\Local\Temp\1CC00654114D7F8D4677BD2025E9DB2F\3\24_news\24_news\Views\User\Dangnhap.cshtml"
             
        

#line default
#line hidden

#line 7 "C:\Users\binhh\AppData\Local\Temp\1CC00654114D7F8D84994677BD2025E9DB2F\3\24_news\24_news\Views\User\Dangnhap.cshtml"
             
		}

#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Dangnhap_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Dangnhap_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\binhh\AppData\Local\Temp\A3DBA79CCF242399955433B9B9959ECD5E74\6\24_news\24_news\Views\User\Dangnhap.cshtml"
  
    ViewBag.Title = "Dangnhap";
    Layout = "~/Views/Shared/_LayoutLogin.cshtml";


#line default
#line hidden

#line 2 "C:\Users\binhh\AppData\Local\Temp\A3DBA79CCF242399955433B9B9959ECD5E74\6\24_news\24_news\Views\User\Dangnhap.cshtml"
        using (Html.BeginForm())
        {
            

#line default
#line hidden

#line 3 "C:\Users\binhh\AppData\Local\Temp\A3DBA79CCF242399955433B9B9959ECD5E74\6\24_news\24_news\Views\User\Dangnhap.cshtml"
       __o = Html.ValidationSummary(true);


#line default
#line hidden

#line 4 "C:\Users\binhh\AppData\Local\Temp\A3DBA79CCF242399955433B9B9959ECD5E74\6\24_news\24_news\Views\User\Dangnhap.cshtml"
                                         
        

#line default
#line hidden

#line 5 "C:\Users\binhh\AppData\Local\Temp\A3DBA79CCF242399955433B9B9959ECD5E74\6\24_news\24_news\Views\User\Dangnhap.cshtml"
             
        

#line default
#line hidden

#line 6 "C:\Users\binhh\AppData\Local\Temp\A3DBA79CCF242399955433B9B9959ECD5E74\6\24_news\24_news\Views\User\Dangnhap.cshtml"
             
        

#line default
#line hidden

#line 7 "C:\Users\binhh\AppData\Local\Temp\A3DBA79CCF242399955433B9B9959ECD5E74\6\24_news\24_news\Views\User\Dangnhap.cshtml"
             
		}

#line default
#line hidden
}
}
}
