//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Views_User_Dangky_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Views_User_Dangky_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\Dangky.cshtml"
  
    Layout = null;


#line default
#line hidden

#line 2 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\Dangky.cshtml"
                    using(Html.BeginForm())
                    {
                        

#line default
#line hidden

#line 3 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\Dangky.cshtml"
                            __o = Url.Action("Index", "Home");


#line default
#line hidden

#line 4 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\Dangky.cshtml"
                                                                                                                           
                        

#line default
#line hidden

#line 5 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\Dangky.cshtml"
                                                                                                

                        

#line default
#line hidden

#line 6 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\Dangky.cshtml"
                       __o = Html.TextBox("HotenND");


#line default
#line hidden

#line 7 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\Dangky.cshtml"
                       __o = ViewData["Loi1"];


#line default
#line hidden

#line 8 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\Dangky.cshtml"
                              

                        

#line default
#line hidden

#line 9 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\Dangky.cshtml"
                       __o = Html.TextBox("TenDN");


#line default
#line hidden

#line 10 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\Dangky.cshtml"
                       __o = ViewData["Loi2"];


#line default
#line hidden

#line 11 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\Dangky.cshtml"
                              

                        

#line default
#line hidden

#line 12 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\Dangky.cshtml"
                       __o = Html.Password("Matkhau");


#line default
#line hidden

#line 13 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\Dangky.cshtml"
                       __o = ViewData["Loi3"];


#line default
#line hidden

#line 14 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\Dangky.cshtml"
                              
                        

#line default
#line hidden

#line 15 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\Dangky.cshtml"
                       __o = Html.Password("Matkhaunhaplai");


#line default
#line hidden

#line 16 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\Dangky.cshtml"
                       __o = ViewData["Loi4"];


#line default
#line hidden

#line 17 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\Dangky.cshtml"
                              
                        

#line default
#line hidden

#line 18 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\Dangky.cshtml"
                       __o = Html.TextBox("Dienthoai");


#line default
#line hidden

#line 19 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\Dangky.cshtml"
                       __o = ViewData["Loi6"];


#line default
#line hidden

#line 20 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\Dangky.cshtml"
                              
                        

#line default
#line hidden

#line 21 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\Dangky.cshtml"
                       __o = Html.TextBox("Email");


#line default
#line hidden

#line 22 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\Dangky.cshtml"
                       __o = ViewData["Loi5"];


#line default
#line hidden

#line 23 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\Dangky.cshtml"
                              
                        

#line default
#line hidden

#line 24 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\Dangky.cshtml"
                              
                        

#line default
#line hidden

#line 25 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\Dangky.cshtml"
                                                                

                        

#line default
#line hidden

#line 26 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\Dangky.cshtml"
                              
                    }

#line default
#line hidden

#line 27 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\Dangky.cshtml"
                                         __o = Url.Action( "Dangnhap", "User");


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Dangky_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Dangky_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\Dangky.cshtml"
  
    Layout = null;


#line default
#line hidden

#line 2 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\Dangky.cshtml"
                            __o = Url.Action("Index", "Home");


#line default
#line hidden

#line 3 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\Dangky.cshtml"
                       __o = Html.TextBox("HotenND");


#line default
#line hidden

#line 4 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\Dangky.cshtml"
                       __o = ViewData["Loi1"];


#line default
#line hidden

#line 5 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\Dangky.cshtml"
                       __o = Html.TextBox("TenDN");


#line default
#line hidden

#line 6 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\Dangky.cshtml"
                       __o = ViewData["Loi2"];


#line default
#line hidden

#line 7 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\Dangky.cshtml"
                       __o = Html.Password("Matkhau");


#line default
#line hidden

#line 8 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\Dangky.cshtml"
                       __o = ViewData["Loi3"];


#line default
#line hidden

#line 9 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\Dangky.cshtml"
                       __o = Html.Password("Matkhaunhaplai");


#line default
#line hidden

#line 10 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\Dangky.cshtml"
                       __o = ViewData["Loi4"];


#line default
#line hidden

#line 11 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\Dangky.cshtml"
                       __o = Html.TextBox("Dienthoai");


#line default
#line hidden

#line 12 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\Dangky.cshtml"
                       __o = ViewData["Loi6"];


#line default
#line hidden

#line 13 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\Dangky.cshtml"
                       __o = Html.TextBox("Email");


#line default
#line hidden

#line 14 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\Dangky.cshtml"
                       __o = ViewData["Loi5"];


#line default
#line hidden

#line 15 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\Dangky.cshtml"
                                        __o = Url.Action( "Dangnhap", "User");


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Dangky_cshtml : System.Web.WebPages.WebPage {
#line hidden
public _Page_Dangky_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\binhh\AppData\Local\Temp\1CC00654114D7F8D84994677BD2025E9DB2F\3\24_news\24_news\Views\User\Dangky.cshtml"
                    \Local\Temp\1CC00654114D7F8D84994677BD2025E9DB2F\3\24_news\24_news\Vi

#line default
#line hidden

#line 2 "C:\Users\binhh\AppData\Local\Temp\1CC00654114D7F8D84994677BD2025E9DB2F\3\24_news\24_news\Views\User\Dangky.cshtml"
                                                                                            \User\Dangky.cshtml"
  

#line default
#line hidden

#line 3 "C:\Users\binhh\AppData\Local\Temp\1CC00654114D7F8D84994677BD2025E9DB2F\3\24_news\24_news\Views\User\Dangky.cshtml"
                          \binhh\AppData\Local\Tem

#line default
#line hidden

#line 4 "C:\Users\binhh\AppData\Local\Temp\1CC00654114D7F8D84994677BD2025E9DB2F\3\24_news\24_news\Views\User\Dangky.cshtml"
                          \binhh\AppData\Local\Tem

#line default
#line hidden

#line 5 "C:\Users\binhh\AppData\Local\Temp\1CC00654114D7F8D84994677BD2025E9DB2F\3\24_news\24_news\Views\User\Dangky.cshtml"
                          \binhh\AppData\Local\T

#line default
#line hidden

#line 6 "C:\Users\binhh\AppData\Local\Temp\1CC00654114D7F8D84994677BD2025E9DB2F\3\24_news\24_news\Views\User\Dangky.cshtml"
                          \binhh\AppData\Local\T

#line default
#line hidden

#line 7 "C:\Users\binhh\AppData\Local\Temp\1CC00654114D7F8D84994677BD2025E9DB2F\3\24_news\24_news\Views\User\Dangky.cshtml"
                                                            114D7F8D84994677BD2025E9

#line default
#line hidden

#line 8 "C:\Users\binhh\AppData\Local\Temp\1CC00654114D7F8D84994677BD2025E9DB2F\3\24_news\24_news\Views\User\Dangky.cshtml"
                          \binhh\AppData\Local


#line default
#line hidden
}
}
}
7F8D84994677BD2025E9DB2F\3\24_news\24_news\Views\User\Dangky.cshtml"
       

#line default
#line hidden
}
}
}
4994677BD2025E9DB2F\3\24_news\24_news\Views\User\Dangky.cshtml"
       

#line default
#line hidden
}
}
}
Views\User\Dangky.cshtml"
         
    }

#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Dangky_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Dangky_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\binhh\AppData\Local\Temp\A3DBA79CCF242399955433B9B9959ECD5E74\6\24_news\24_news\Views\User\Dangky.cshtml"
  
    ViewBag.Title = "Dangky";
    Layout = "~/Views/Shared/_LayoutLogin.cshtml";


#line default
#line hidden

#line 2 "C:\Users\binhh\AppData\Local\Temp\A3DBA79CCF242399955433B9B9959ECD5E74\6\24_news\24_news\Views\User\Dangky.cshtml"
    using (Html.BeginForm())
    {
        

#line default
#line hidden

#line 3 "C:\Users\binhh\AppData\Local\Temp\A3DBA79CCF242399955433B9B9959ECD5E74\6\24_news\24_news\Views\User\Dangky.cshtml"
   __o = Html.ValidationSummary(true);


#line default
#line hidden

#line 4 "C:\Users\binhh\AppData\Local\Temp\A3DBA79CCF242399955433B9B9959ECD5E74\6\24_news\24_news\Views\User\Dangky.cshtml"
                                     
        

#line default
#line hidden

#line 5 "C:\Users\binhh\AppData\Local\Temp\A3DBA79CCF242399955433B9B9959ECD5E74\6\24_news\24_news\Views\User\Dangky.cshtml"
             
        

#line default
#line hidden

#line 6 "C:\Users\binhh\AppData\Local\Temp\A3DBA79CCF242399955433B9B9959ECD5E74\6\24_news\24_news\Views\User\Dangky.cshtml"
             
        

#line default
#line hidden

#line 7 "C:\Users\binhh\AppData\Local\Temp\A3DBA79CCF242399955433B9B9959ECD5E74\6\24_news\24_news\Views\User\Dangky.cshtml"
             
        

#line default
#line hidden

#line 8 "C:\Users\binhh\AppData\Local\Temp\A3DBA79CCF242399955433B9B9959ECD5E74\6\24_news\24_news\Views\User\Dangky.cshtml"
             
        

#line default
#line hidden

#line 9 "C:\Users\binhh\AppData\Local\Temp\A3DBA79CCF242399955433B9B9959ECD5E74\6\24_news\24_news\Views\User\Dangky.cshtml"
             
        

#line default
#line hidden

#line 10 "C:\Users\binhh\AppData\Local\Temp\A3DBA79CCF242399955433B9B9959ECD5E74\6\24_news\24_news\Views\User\Dangky.cshtml"
             
        

#line default
#line hidden

#line 11 "C:\Users\binhh\AppData\Local\Temp\A3DBA79CCF242399955433B9B9959ECD5E74\6\24_news\24_news\Views\User\Dangky.cshtml"
             
    }

#line default
#line hidden
}
}
}
