//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Views_User_SuaTinTuc_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Views_User_SuaTinTuc_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\SuaTinTuc.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\SuaTinTuc.cshtml"
  
    ViewBag.Title = "SuaTinTuc";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";


#line default
#line hidden

#line 3 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\SuaTinTuc.cshtml"
using (Html.BeginForm())
{
    

#line default
#line hidden

#line 4 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\SuaTinTuc.cshtml"
__o = Html.AntiForgeryToken();


#line default
#line hidden

#line 5 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\SuaTinTuc.cshtml"
                            
    
    

#line default
#line hidden

#line 6 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\SuaTinTuc.cshtml"
   __o = Html.ValidationSummary(true, "", new { @class = "text-danger" });


#line default
#line hidden

#line 7 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\SuaTinTuc.cshtml"
   __o = Html.HiddenFor(model => model.MaTinTuc);


#line default
#line hidden

#line 8 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\SuaTinTuc.cshtml"
       __o = Html.LabelFor(model => model.TenTinTuc, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 9 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C7513       ws\2= Html.LabelFor(model => model.ChiTiet, htmlAttributes: new { @class 4_"control-label col-md-2" })news\Views\User\SuaTinTuc.cshtml"
           __o = Html.EditorFor(model => model.TenTinTuc, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hiddenHtml.EditorFor(model => model.ChiTiet, new { htmlAttributes = new { @class = "form-control" } })

#line 10 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\SuaTinTuc.cshtml"
           __o = Html.ValidationMe           r(model => ValidationMessageFornTinTuc, "", new { @class""," });


#line textndanger

#line 11 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\SuaTinTuc.cshtml"
       __o = Html.LabelFor(model => mod        htmlAttribLabelFor { @class = "conAnhBiabemd-2" });

:line default
#licontrol-label col-mdi2
#le 12 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\SuaTinTuc.cshtml"
           __o = Html.EditorFor(model => model.ChiTiet, new { htmEditorFor@class = "form-cAnhBia }new { htmlAttributes =;


#line defaform
controlhid }den

#line 13 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\SuaTinTuc.cshtml"
           __o = Html.Validation           For(model =ValidationMessageForChiTiet, "", new { @clas"",r" });


#linetextedanger

#line 14 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\SuaTinTuc.cshtml"
       __o = Html.LabelFor(model => mo        htmlAttribLabelFor { @class = "conNgayCapNhatab-md-2" });

:#line default
#lcontrol-label col-mdh2
#ne 15 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\SuaTinTuc.cshtml"
           __o = Html.EditorFor(model => model.AnhBia, new { htmEditorFor@class = "form-cNgayCapNhat" new { htmlAttributes =);


#line defformcontrol hi }dden

#line 16 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\SuaTinTuc.cshtml"
           __o = Html.Validatio           eFor(model ValidationMessageFor.AnhBia, "", new { @class = """,;


#line defatext
dangerline 17 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\SuaTinTuc.cshtml"
       __o = Html.LabelFor(model => model.N        htmlAttribLabelFor { @class = "conMaCDco" });


#li: default
#line hcontrol-label col-mdn2ne  "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\SuaTinTuc.cshtml"
           __o = Html.EditorFor(model => model.NgayCapNhat, new { htmEditorFor@class = "form-cMaCD);new { htmlAttributes =

#line defaultformncontrolen }

#line 19 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\SuaTinTuc.cshtml"
           __o = Html.ValidationMess           model => moValidationMessageForCapNhat, "", new { @cl"",ger" });


#litextddangeren

#line 20 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\SuaTinTuc.cshtml"
       __o = Html.LabelFor(model => ionMessageFor(model => model.MaCD, "", new { @class = 22ext-danger" });


#line default
#line hidden

#line 23 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\SuaTinTuc.cshtml"
          
}

#line default
#line hidden

#line 24 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\SuaTinTuc.cshtml"
__o = Html.ActionLink("Back to List", "Index");


#line default
#line hidden
}
}
}
