//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Views_User_ThemTinTuc_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Views_User_ThemTinTuc_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\ThemTinTuc.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\ThemTinTuc.cshtml"
  
    ViewBag.Title = "ThemTinTuc";
    Layout = "~/Views/Shared/_Layout.cshtml";


#line default
#line hidden

#line 3 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\ThemTinTuc.cshtml"
using (Html.BeginForm("ThemTinTuc", "User", FormMethod.Post, new { @enctype = "multipart/form-data"}))
{


#line default
#line hidden

#line 4 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\ThemTinTuc.cshtml"
__o = Html.AntiForgeryToken();


#line default
#line hidden

#line 5 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\ThemTinTuc.cshtml"
                        



#line default
#line hidden

#line 6 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\ThemTinTuc.cshtml"
__o = Html.ValidationSummary(true);


#line default
#line hidden

#line 7 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\ThemTinTuc.cshtml"
   __o = Html.LabelFor(model => model.TenTinTuc, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 8 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\ThemTinTuc.cshtml"
       __o = Html.EditorFor(model => model.TenTinTuc, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 9 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\ThemTinTuc.cshtml"
       __o = Html.ValidationMessageFor(model => model.TenTinTuc, "", new { @class = "text-danger" });


#line default
#line hidden

#line 10 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\ThemTinTuc.cshtml"
   __o = Html.LabelFor(model => model.ChiTiet, new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 11 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\ThemTinTuc.cshtml"
   __o = Html.LabelFor(model => model.AnhBia, new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 12 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\ThemTinTuc.cshtml"
       __o = ViewBag.ThongBao;


#line default
#line hidden

#line 13 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\ThemTinTuc.cshtml"
   __o = Html.LabelFor(model => model.NgayCapNhat, new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 14 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\ThemTinTuc.cshtml"
       __o = Html.ValidationMessageFor(model => model.NgayCapNhat);


#line default
#line hidden

#line 15 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\ThemTinTuc.cshtml"
   __o = Html.LabelFor(model => model.MaCD, new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 16 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\ThemTinTuc.cshtml"
       __o = Html.DropDownList("MaCD");


#line default
#line hidden

#line 17 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\ThemTinTuc.cshtml"
      
}

#line default
#line hidden

#line 18 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\ThemTinTuc.cshtml"
__o = Html.ActionLink("Về Trang Chủ", "Index", "Home");


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_ThemTinTuc_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_ThemTinTuc_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\ThemTinTuc.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\ThemTinTuc.cshtml"
  
    ViewBag.Title = "ThemTinTuc";
    Layout = "~/Views/Shared/_Layout.cshtml";


#line default
#line hidden

#line 3 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\ThemTinTuc.cshtml"
using (Html.BeginForm()) 
{
    

#line default
#line hidden

#line 4 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\ThemTinTuc.cshtml"
__o = Html.AntiForgeryToken();


#line default
#line hidden

#line 5 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\ThemTinTuc.csht                             
    
    

#line default
#line hidden

#line 6 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\ThemTin.cshtml"
   __o = Html.ValidationSummary(true, "", new { @class = "text-danger" });


#line default
#line hidden

#line 7 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\ThemTin   tml"
       __o = Html.LabelFor(model => model.TenTinTuc, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 8 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\ThemTin       
           __o = Html.EditorFor(model => model.TenTinTuc, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 9 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\ThemTin       
           __o = Html.ValidationMessageFor(model => model.TenTinTuc, "", new { @class = "text-danger" });


#line default
#line hidden

#line 10 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\ThemTin   tml"
       __o = Html.LabelFor(model => model.ChiTiet, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 11 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24   4_newsHtml.LabelFor(model => model.AnhBia, new { @class = "control-label col-md-2" })\Views\User\ThemTin       
           __o = Html.EditorFor(model => model.ChiTiet, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#lViewBag.ThongBaone 12 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\ThemTin       
           __o = Html.ValidationMessageFor(model => model.ChiTiet, "", new { @classNgayCapNhatxt-danger" });


#line default
#line hidden

#line 13 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\ThemTin   tml"
       __o = Html.LabelFor(model => model.AnhBiaHtml.ValidationMessageFor(model => modeltNgayCapNhat): new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 14 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\ThemTin       MaCD  __o = ViewBag.ThongBao;


#line default
#line hidden

#line 15 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\ThemTin   tml"
       __o = Html.LabelFor(model => model.DropDownListr"MaCD"ntrol-label col-md-2" });


#line default
#line hidden

#line 16 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Vi      38EF246FAC4D82625\2\24       ws\Views\User\ThemTin18c.cshtml"
           __o = ;


#line default
#line hidden

#line 19 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\
Use      .cshtml"
          
}

#line default
#line hidden

#line 20 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\ThemTinTuc.cshtml"
__o = Html.ActionLink("Back to List", "Index");


#line default
#line hidden
}
}
}
