//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

#line 1 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\TinTuc.cshtml"
using _24_news.Models;

#line default
#line hidden

#line 2 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\TinTuc.cshtml"
using PagedList.Mvc;

#line default
#line hidden

public class _Page_TinTuc_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
#line 4 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\TinTuc.cshtml"
public System.Web.WebPages.HelperResult Truncate(string input, int length) 
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 5 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\TinTuc.cshtml"
 
    if (input.Length < length)
    {
        

#line default
#line hidden

#line 6 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\TinTuc.cshtml"
   __o = input;


#line default
#line hidden

#line 7 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\TinTuc.cshtml"
              
    }
    else
    {
        

#line default
#line hidden

#line 8 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\TinTuc.cshtml"
   __o = input.Substring(0, length);


#line default
#line hidden

#line 9 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\TinTuc.cshtml"
                                                   
    }


#line default
#line hidden
});

#line 10 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\TinTuc.cshtml"
}
#line default
#line hidden

public _Page_TinTuc_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 3 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\TinTuc.cshtml"
__o = model;


#line default
#line hidden

#line 11 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\TinTuc.cshtml"
  
    ViewBag.Title = "TinTuc";
    Layout = "~/Views/Shared/_Layout.cshtml";


#line default
#line hidden

#line 12 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\TinTuc.cshtml"
__o = Html.ActionLink("Thêm tin mới", "ThemTinTuc");


#line default
#line hidden

#line 13 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\TinTuc.cshtml"
       __o = Html.DisplayNameFor(model => model.First().TenTinTuc);


#line default
#line hidden

#line 14 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\TinTuc.cshtml"
       __o = Html.DisplayNameFor(model => model.First().ChiTiet);


#line default
#line hidden

#line 15 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\TinTuc.cshtml"
       __o = Html.DisplayNameFor(model => model.First().AnhBia);


#line default
#line hidden

#line 16 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\TinTuc.cshtml"
       __o = Html.DisplayNameFor(model => model.First().NgayCapNhat);


#line default
#line hidden

#line 17 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\TinTuc.cshtml"
       __o = Html.DisplayNameFor(model => model.First().MaCD);


#line default
#line hidden

#line 18 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\TinTuc.cshtml"
    foreach (var item in Model)
    {
        

#line default
#line hidden

#line 19 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\TinTuc.cshtml"
           __o = Html.DisplayFor(modelItem => item.TenTinTuc);


#line default
#line hidden

#line 20 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\TinTuc.cshtml"
           __o = Truncate(item.ChiTiet, 100);


#line default
#line hidden

#line 21 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\TinTuc.cshtml"
                     __o = Url.Content("~/Images/anhBiaTinTuc/" + item.AnhBia);


#line default
#line hidden

#line 22 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\TinTuc.cshtml"
           __o = Html.DisplayFor(modelItem => item.NgayCapNhat);


#line default
#line hidden

#line 23 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\TinTuc.cshtml"
           __o = Html.DisplayFor(modelItem => item.CHUDE.TenChuDe);


#line default
#line hidden

#line 24 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\TinTuc.cshtml"
           __o = Html.ActionLink("Sửa", "SuaTin", new { id = item.MaTinTuc });


#line default
#line hidden

#line 25 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\TinTuc.cshtml"
           __o = Html.ActionLink("Chi tiết", "Chitiet", new { id = item.MaTinTuc });


#line default
#line hidden

#line 26 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\TinTuc.cshtml"
           __o = Html.ActionLink("Xóa", "Xoatin", new { id = item.MaTinTuc });


#line default
#line hidden

#line 27 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\TinTuc.cshtml"
             
    }

#line default
#line hidden

#line 28 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\TinTuc.cshtml"
  __o = Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber;


#line default
#line hidden

#line 29 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\TinTuc.cshtml"
                                                              __o = Model.PageCount;


#line default
#line hidden

#line 30 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\User\TinTuc.cshtml"
__o = Html.PagedListPager(Model, page => Url.Action("TinTuc", new { page = page}));


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Views_User_TinTuc_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Views_User_TinTuc_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\TinTuc.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\TinTuc.cshtml"
  
    ViewBag.Title = "TinTuc";
    Layout = "~/Views/Shared/_Layout.cshtml";


#line default
#line hidden

#line 3 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\TinTuc.cshtml"
__o = Html.ActionLink("Create New", "Create");


#line default
#line hidden

#line 4 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\TinTuc.cshtml"
       __o = Html.DisplayNameFor(model => model.TenTinTuc);


#line default
#line hidden

#line 5 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\TinTuc.cshtml"
       __o = Html.DisplayNameFor(model => model.ChiTiet);


#line default
#line hidden

#line 6 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\TinTuc.cshtml"
       __o = Html.DisplayNameFor(model => model.AnhBia);


#line default
#line hidden

#line 7 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\TinTuc.cshtml"
       __o = Html.DisplayNameFor(model => model.NgayCapNhat);


#line default
#line hidden

#line 8 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\TinTuc.cshtml"
       __o = Html.DisplayNameFor(model => model.MaCD);


#line default
#line hidden

#line 9 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\TinTuc.cshtml"
foreach (var item in Model) {
    

#line default
#line hidden

#line 10 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\TinTuc.cshtml"
       __o = Html.DisplayFor(modelItem => item.TenTinTuc);


#line default
#line hidden

#line 11 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\TinTuc.cshtml"
       __o = Html.DisplayFor(modelItem => item.ChiTiet);


#line default
#line hidden

#line 12 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\TinTuc.cshtml"
       __o = Html.DisplayFor(modelItem => item.AnhBia);


#line default
#line hidden

#line 13 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\TinTuc.cshtml"
       __o = Html.DisplayFor(modelItem => item.NgayCapNhat);


#line default
#line hidden

#line 14 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\TinTuc.cshtml"
       __o = Html.DisplayFor(modelItem => item.MaCD);


#line default
#line hidden

#line 15 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\TinTuc.cshtml"
       __o = Html.ActionLink("Edit", "Edit", new { id=item.MaTinTuc });


#line default
#line hidden

#line 16 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\TinTuc.cshtml"
       __o = Html.ActionLink("Details", "Details", new { id=item.MaTinTuc });


#line default
#line hidden

#line 17 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\User\TinTuc.cshtml"
EF246FAC4D82625\2\24_news\24_news\Views\User\TinTuc.cshtml"
         
}

#line default
#line hidden
}
}
}
