//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Views_Home_Single_cshtml : System.Web.WebPages.WebPage {
#line hidden
public _Page_Views_Home_Single_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\binhh\AppData\Local\Temp\1CC00654114D7F8D84994677BD2025E9DB2F\3\24_news\24_news\Views\Home\Single.cshtml"
  
    ViewBag.Title = "Single";
    Layout = "~/Views/Shared/_Layout.cshtml";


#line default
#line hidden
}
}
}
