//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page__Layout_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page__Layout_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\Shared\_Layout.cshtml"
                        __o = Url.Action("Index", "Home");


#line default
#line hidden

#line 2 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\Shared\_Layout.cshtml"
                                                              __o = Url.Action( "Dangnhap", "User");


#line default
#line hidden

#line 3 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\Shared\_Layout.cshtml"
                                                              __o = Url.Action( "Dangky", "User");


#line default
#line hidden

#line 4 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\Shared\_Layout.cshtml"
                                                 __o = Url.Action("Index", "Home");


#line default
#line hidden

#line 5 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\Shared\_Layout.cshtml"
                                                 __o = Url.Action( "Dangnhap", "User");


#line default
#line hidden

#line 6 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\Shared\_Layout.cshtml"
                                                 __o = Url.Action( "Dangky", "User");


#line default
#line hidden

#line 7 "C:\Users\buiha\AppData\Local\Temp\31019042F66F715AAA201D8E2132C751303B\2\24_news\24_news\Views\Shared\_Layout.cshtml"
   __o = RenderBody();


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page__Layout_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page__Layout_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\Shared\_Layout.cshtml"
                                                          __o = Url.Action( "Dangnhap", "User");


#line default
#line hidden

#line 2 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\Shared\_Layout.cshtml"
                                                          __o = Url.Action( "Dangky", "User");


#line default
#line hidden

#line 3 "C:\Users\binhh\AppData\Local\Temp\D526AC1EC9F7F203AC638EF246FAC4D82625\2\24_news\24_news\Views\Shared\_Layout.cshtml"
   __o = RenderBody();


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page__Layout_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page__Layout_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\binhh\AppData\Local\Temp\1CC00654114D7F8D84994677BD2025E9DB2F\3\24_news\24_news\Views\Shared\_Layout.cshtml"
                       __o = Html.ActionLink("Đăng nhập", "Dangnhap", "User");


#line default
#line hidden

#line 2 "C:\Users\binhh\AppData\Local\Temp\1CC00654114D7F8D84994677BD2025E9DB2F\3\24_news\24_news\Views\Shared\_Layout.cshtml"
                       __o = Html.ActionLink("Đăng ký", "Dangky", "User");


#line default
#line hidden

#line 3 "C:\Users\binhh\AppData\Local\Temp\1CC00654114D7F8D84994677BD2025E9DB2F\3\24_news\24_news\Views\Shared\_Layout.cshtml"
   __o = RenderBody();


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page__Layout_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page__Layout_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\binhh\AppData\Local\Temp\1CC00654114D7F8D84994677BD2025E9DB2F\2\24_news\24_news\Views\Shared\_Layout.cshtml"
                       __o = Html.ActionLink("Đăng nhập", "Dangnhap", "User");


#line default
#line hidden

#line 2 "C:\Users\binhh\AppData\Local\Temp\1CC00654114D7F8D84994677BD2025E9DB2F\2\24_news\24_news\Views\Shared\_Layout.cshtml"
                       __o = Html.ActionLink("Đăng ký", "Dangky", "User");


#line default
#line hidden

#line 3 "C:\Users\binhh\AppData\Local\Temp\1CC00654114D7F8D84994677BD2025E9DB2F\2\24_news\24_news\Views\Shared\_Layout.cshtml"
   __o = RenderBody();


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page__Layout_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page__Layout_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\buiha\AppData\Local\Temp\A3DBA79CCF242399955433B9B9959ECD5E74\10\24_news\24_news\Views\Shared\_Layout.cshtml"
                       __o = Html.ActionLink("Đăng nhập", "Dangnhap", "User");


#line default
#line hidden

#line 2 "C:\Users\buiha\AppData\Local\Temp\A3DBA79CCF242399955433B9B9959ECD5E74\10\24_news\24_news\Views\Shared\_Layout.cshtml"
                       __o = Html.ActionLink("Đăng ký", "Dangky", "User");


#line default
#line hidden

#line 3 "C:\Users\buiha\AppData\Local\Temp\A3DBA79CCF242399955433B9B9959ECD5E74\10\24_news\24_news\Views\Shared\_Layout.cshtml"
ws\Shared\_Layout.cshtml"
                  y();


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page__Layout_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page__Layout_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\binhh\AppData\Local\Temp\A3DBA79CCF242399955433B9B9959ECD5E74\6\24_news\24_news\Views\Shared\_Layout.cshtml"
                                         __o = ;


#line  efault
#line hidden

#line 2 "C:\Users\binhh\AppData\Local\Temp\A3DBA79CCF242399955433B9B9959ECD5E74\6\24_news\24_news\Views\Shared\_Layout.cshtml"
   __o = RenderBody();


#line default
#line hidden
}
}
}
